src/main/java/com/qa/cinema/persistence/User.java, src/main/java/com/qa/cinema/rest/UserEndpoint.java, src/main/java/com/qa/cinema/service/DBMovieService.java, src/main/java/com/qa/cinema/service/DBUserService.java, src/main/java/com/qa/cinema/service/UserService.java
Classes added.
(Builds successfully with Maven)
=> QA-16 User Backend

src/main/java/com/qa/cinema/persistence/Movie.java, src/main/java/com/qa/cinema/rest/MovieEndpoint.java, src/main/java/com/qa/cinema/service/DBMovieService.java, src/main/java/com/qa/cinema/service/MapMovieService.java, src/main/java/com/qa/cinema/service/MovieService.java
=> QA-2 #comment Added back-end CRUD functionality, Nikesh & Scott

src/main/java/com/qa/cinema/persistence/Movie.java
=> QA-2 #comment Changed releaseDate attribute to be of type 'date' - Nikesh & Scott

src/main/java/com/qa/cinema/rest/ShowingEndpoint.java, src/main/java/com/qa/cinema/service/DBShowingService.java
=> QA-34 #comment Showing Endpoint created and Service update method fixed

src/main/java/com/qa/cinema/rest/ShowingEndpoint.java, src/main/java/com/qa/cinema/service/DBShowingService.java, src/main/java/com/qa/cinema/service/ShowingService.java
=> QA-37 #comment New functionality, find by movieId method added to Service

src/main/webapp/app/feature/movie/add/add-movie-partial.html, src/main/webapp/app/feature/movie/delete/delete-movie-controller.js, src/main/webapp/app/feature/movie/delete/delete-movie-partial.html
=> QA-12 #comment added extra fields to add movie

src/main/java/com/qa/cinema/rest/MovieEndpoint.java, src/main/java/com/qa/cinema/service/DBMovieService.java, src/main/java/com/qa/cinema/service/MapMovieService.java, src/main/java/com/qa/cinema/service/MovieService.java
=> QA-63 #comment created 'search by genre' feature on back-end

src/main/webapp/app/feature/movie/add/add-movie-controller.js, src/main/webapp/app/feature/movie/add/add-movie-partial.html, src/main/webapp/app/feature/movie/delete/delete-movie-controller.js, src/main/webapp/app/feature/movie/delete/delete-movie-partial.html, src/main/webapp/app/feature/movie/update/update-movie-controller.js, src/main/webapp/app/feature/movie/update/update-movie-partial.html, src/main/webapp/app/service/dal/dal.js, src/main/webapp/app/service/dal/movie.js
=> QA-12 #comment corrected update function and tested on postman

src/main/java/com/qa/cinema/rest/ShowingEndpoint.java, src/main/java/com/qa/cinema/service/DBShowingService.java, src/main/java/com/qa/cinema/service/ShowingService.java
=> QA-34 #comment Find by screen id method added to Service

src/main/java/com/qa/cinema/persistence/Screen.java, src/main/java/com/qa/cinema/persistence/User.java, src/main/java/com/qa/cinema/rest/ScreenEndpoint.java, src/main/java/com/qa/cinema/service/DBScreenService.java, src/main/java/com/qa/cinema/service/ScreenService.java
POJO, Service, and Endpoint created.
(Builds successfully in Maven)
=> QA-58 Screen backend created

src/main/webapp/app/feature/movie/get-by-title/get-by-title.html
=> QA-32 #comment Started stylising individual movie page

src/main/webapp/app/app.js, src/main/webapp/app/feature/login/parentController.js, src/main/webapp/app/global-functions.js, src/main/webapp/app/service/auth.js, src/main/webapp/index.html
=> QA-92 #comment implemented cookies and dynamic login/logout button

src/main/webapp/app/app-state-manager.js, src/main/webapp/app/feature/showing/get-by-movie/get-showing-by-movie-controller.js, src/main/webapp/app/feature/showing/get-by-movie/get-showing-by-movie.html, src/main/webapp/app/service/dal/showing.js, src/main/webapp/index.html
=> QA-34 #comment Get Showing by Movie Id view added

src/main/webapp/app/feature/movie/get/get-movie-controller.js, src/main/webapp/app/feature/movie/get/get-movie-partial.html, src/main/webapp/index.html
=> QA-93 #comment get movies displays posters, modal is fixed, index.html styling changed

src/main/webapp/app/feature/showing/delete/delete-showing.html, src/main/webapp/app/service/dal/showing.js
=> QA-34 #comment Showing delete view fixed

src/main/java/com/qa/cinema/persistence/Seat.java, src/main/java/com/qa/cinema/rest/MovieEndpoint.java, src/main/java/com/qa/cinema/service/DBSeatService.java, src/main/java/com/qa/cinema/service/DBTicketService.java, src/main/webapp/app/feature/login/login.js, src/main/webapp/app/feature/movie/get-by-genre/get-movie-by-genre-controller.js, src/main/webapp/app/feature/movie/get-by-title/get-movie-by-title-controller.js, src/main/webapp/app/feature/seat/delete/delete-seat-controller.js, src/main/webapp/app/feature/ticket/add/add-ticket-controller.js, src/main/webapp/app/feature/ticket/update/update-ticket-controller.js
Remotely built and analysed with SonarQube, builds fine. Not all bugs dealt with, but some improvement so far.
=> Taken care of most of Sonarqube complaints

pom.xml, src/main/java/com/qa/cinema/persistence/Ticket.java, src/main/java/com/qa/cinema/rest/EmailEndpoint.java, src/main/java/com/qa/cinema/rest/TicketEndpoint.java, src/main/java/com/qa/cinema/service/DBTicketService.java, src/main/java/com/qa/cinema/service/EmailService.java, src/main/java/com/qa/cinema/service/MimeEmailService.java, src/main/java/com/qa/cinema/service/TicketService.java, src/main/resources/import.sql, wildfly-10.0.0.Final/wildfly-10.0.0.Final/standalone/configuration/standalone.xml
- The wildfly/.../standalone.xml file on github must be put in your local wildfly folder
=> #comment Email back-end implemented. Ticket backend updated to get all tickets for an order ID

src/main/webapp/app/feature/movie/get-by-title/get-by-title.html, src/main/webapp/app/feature/showing/get-by-movie/get-showing-by-movie-controller.js
=> QA-39 #comment added show screenings scheduled for today and tomorrow

src/main/java/com/qa/cinema/service/DBMovieService.java, src/main/webapp/app/feature/movie/get-by-title/get-by-title.html, src/main/webapp/app/feature/movie/search/search-results-controller.js, src/main/webapp/app/feature/movie/search/search-results.html, src/main/webapp/css/globalStyle.css
=> QA-98 fixes

src/main/java/com/qa/cinema/service/DBTicketService.java
=> QA-103 #comment fixed a bad implementation

src/main/java/com/qa/cinema/service/DBTicketService.java
=> QA-15 #comment Updated DBTicketService

src/main/webapp/app/feature/movie/get-by-title/get-by-title.html
=> QA-39 #comment added modal for payment on movie page

src/main/webapp/app/feature/movie/get-by-title/get-by-title.html
=> QA-103 #comment fixed errors

src/main/webapp/app/feature/ticket/get/get-user-tickets-controller.js, src/main/webapp/app/feature/ticket/get/get-user-tickets.html
=> QA-94 #comment Refactored get tickets to use the logged in user's email

src/main/java/com/qa/cinema/service/DBTicketService.java
=> QA-147 #comment Fixed parsing showing date in getPrice

src/main/webapp/app/app-state-manager.js, src/main/webapp/app/feature/aboutUs/about-us-controller.js, src/main/webapp/app/feature/aboutus/about-us.html, src/main/webapp/index.html
=> QA-110 #comment Made about us, and fixed google maps (Hailey & Nikesh)

src/main/webapp/app/app.js, src/main/webapp/app/feature/movie/get-by-title/get-by-title.html, src/main/webapp/app/feature/showing/get-by-movie/get-showing-by-movie-controller.js, src/main/webapp/app/feature/ticket/add/add-ticket-controller.js, src/main/webapp/app/feature/ticket/add/add-ticket-standalone.html, src/main/webapp/app/service/auth.js
=> QA-15 #comment implemented functionality to booking modal on film page

src/main/webapp/app/feature/movie/get-by-title/get-movie-by-title-controller.js, src/main/webapp/app/feature/movie/get/get-movie-controller.js, src/main/webapp/app/feature/movie/search/search-results-controller.js, src/main/webapp/app/global-functions.js
=> QA-2 #comment Refreshing movie pages works on login

src/main/webapp/app/feature/movie/get/get-movie-partial.html
=> QA-139 #comment fixed bugs on coming soon

src/main/webapp/app/feature/movie/get-by-title/get-by-title.html, src/main/webapp/app/feature/ticket/add/add-ticket-controller.js
=> QA-15 #comment fixed seat shower on movie booking page

src/main/webapp/app/feature/movie/get-by-title/get-by-title.html
=> fixed modal link bugs

src/test/java/com/qa/cinema/persistence/MovieTest.java
=> QA-15 #comment started junit testing

src/test/java/com/qa/cinema/persistence/ScreenTest.java, src/test/java/com/qa/cinema/service/DBScreenServiceTest.java
=> QA-162 #comment made tests for Screen POJO

src/main/webapp/app/app-state-manager.js, src/main/webapp/app/feature/orderSummary/all-user-orders.html, src/main/webapp/app/feature/orderSummary/order-summary-controller.js, src/main/webapp/app/feature/orderSummary/order-summary.html, src/main/webapp/app/feature/payment/payment-controller.js, src/main/webapp/app/service/dal/ticket.js
=> QA-112 #comment Mostly working order summary page

src/main/webapp/app/feature/orderSummary/all-user-orders.html, src/main/webapp/app/feature/orderSummary/order-summary-controller.js, src/main/webapp/app/feature/orderSummary/order-summary.html
=> QA-112 #comment Order summary fixed

src/main/webapp/app/feature/orderSummary/all-user-orders.html, src/main/webapp/app/feature/orderSummary/order-summary-controller.js, src/main/webapp/app/feature/orderSummary/order-summary.html, src/main/webapp/app/feature/payment/payment-controller.js, src/main/webapp/app/feature/payment/payment.html, src/main/webapp/app/feature/user/add/add-user-controller.js, src/main/webapp/app/feature/user/add/add-user.html
=> QA-185 #comment Sign up new user fixed

src/main/webapp/app/feature/orderSummary/all-user-orders.html, src/main/webapp/app/feature/orderSummary/order-summary-controller.js, src/main/webapp/app/feature/orderSummary/order-summary.html, src/main/webapp/app/feature/payment/payment-controller.js, src/main/webapp/app/feature/payment/payment.html, src/main/webapp/app/feature/user/add/add-user-controller.js, src/main/webapp/app/feature/user/add/add-user.html
=> QA-183 #comment Script to format card number added

src/main/java/com/qa/cinema/service/DBTicketService.java, src/main/webapp/app/feature/dashboard/dashboard-partial.html, src/main/webapp/css/viewStyleSheets/home/dashboard.css, src/main/webapp/scripts/bootstrap.css
=> Added coming soon and now showing movies to front page

src/main/webapp/app/feature/cookies/cookies.html, src/main/webapp/app/feature/dashboard/dashboard-partial.html, src/main/webapp/app/feature/ticket/add/add-ticket-controller.js, src/main/webapp/app/feature/ticket/add/add-ticket-standalone.html, src/main/webapp/index.html
=> QA-200 #comment book now link working from dashboard and movie page. Auto-populating movie and showing correctly now

src/test/java/com/qa/cinema/persistence/ShowingTest.java
=> QA-208 #comment JUnit test for showing pojo

src/main/webapp/app/app.js, src/main/webapp/app/feature/ticket/add/add-ticket-standalone.html
=> Qa 178 Created and added filter to booking standalone to only show showings in the future

src/main/webapp/app/feature/ticket/add/add-ticket-standalone.html, src/main/webapp/css/viewStyleSheets/ticket/add-ticket-style.css
=> QA-195 #comment fixed modal stretch on quick-book

src/main/webapp/app/feature/movie/get-by-title/get-by-title.html, src/main/webapp/app/feature/payment/payment-controller.js, src/main/webapp/app/feature/showing/get-by-movie/get-showing-by-movie-controller.js, src/main/webapp/app/feature/ticket/add/add-ticket-controller.js, src/main/webapp/app/service/auth.js, src/main/webapp/app/service/dal/ticket.js
=> Qa 186 - Fixed bug when booking ticket from movie page

src/main/webapp/app/feature/payment/payment.html
=> QA-188 #comment right price displayed

src/main/webapp/app/feature/movie/get-by-title/get-by-title.html, src/main/webapp/app/feature/showing/get-by-movie/get-showing-by-movie-controller.js, src/main/webapp/app/feature/ticket/add/add-ticket-controller.js, src/main/webapp/app/feature/ticket/add/add-ticket-standalone.html
=> Qa 164 - added number of available seats when booking ticket

src/main/webapp/app/feature/movie/get/get-movie-partial.html, src/main/webapp/css/viewStyleSheets/movie/get-movie-style.css
=> QA-206 #comment sorted bootstrap on get all movies page

src/main/webapp/app/app-state-manager.js, src/main/webapp/app/app.js, src/main/webapp/css/globalStyle.css, src/main/webapp/index.html
Permissions now added for all pages, most CRUD functions now only accessible by admin - any other role now returns Not Authorised as intended.
Nav-bar changes depending on role, logging in/out updates nav-bar correctly.
Styled the new nav-bar features for customers.
=> QA-199 #comment User roles re-introduced, navbar refactored, styling added

src/main/webapp/app/app.js, src/main/webapp/app/feature/cookies/cookies.html, src/main/webapp/app/feature/help/help.html, src/main/webapp/app/feature/movie/get-by-title/get-by-title.html
=> Qa 178 Sorted out the jumbotron at the top of privacy policy and help page & Added the date filter to the book ticket page via the get movie

src/main/webapp/app/feature/dashboard/dashboard-partial.html
=> Carousel bug fix

src/main/java/com/qa/cinema/service/DBUserService.java, src/main/webapp/app/feature/orderSummary/all-user-orders.html, src/main/webapp/app/feature/orderSummary/order-summary.html
=> QA-185 #comment sign up fixed

src/main/webapp/app/feature/payment/payment.html
=> QA-206 #comment limited input characters on payment page

src/main/webapp/app/feature/dashboard/dashboard-partial.html
=> Qa 178 resized coming soon and edited limits for mobile and fullscreen and updated alt text

src/main/webapp/app/feature/movie/get/get-movie-partial.html, src/main/webapp/app/feature/ticket/add/add-ticket-standalone.html, src/main/webapp/css/viewStyleSheets/home/dashboard.css, src/main/webapp/css/viewStyleSheets/movie/get-movie-style.css, src/test/java/com/qa/cinema/service/DBScreenServiceTest.java
=> QA-213 CSS stuff

src/main/webapp/app/feature/movie/get-by-title/get-by-title.html
=> QA #comment fixed div endings on get-by-title

src/main/webapp/app/feature/movie/add/add-movie-partial.html
=> Qa 178 Submit poster url button

src/main/webapp/css/globalStyle.css
=> QA-bugfix #comment Removed footer height

src/test/java/com/qa/cinema/service/DBMovieServiceTest.java, src/test/java/com/qa/cinema/service/DBUserServiceTest.java, src/test/java/com/qa/cinema/util/user/MergeUser.java, src/test/java/com/qa/cinema/util/user/RemoveUser.java
=> QA-208 #comment extra test for movie and user
